#01_server配置
server:
  port: 8889
#03_logger配置
logging:
  level:
    root: WARN
    "com.tkp": DEBUG
  pattern:
      console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n"
      file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n" 

#04_feign配置
feign:
  okhttp:
    enabled: true 

#06_local project config配置
config:
  cdn:
    host: http://10.130.208.30/tkpmallfilecenter
    source: /WX
    relativePath: /tkp-learn/json/
    imgProperty: png
    isCover: false
    domain: http://wxyl.pension.taikang.com
    imgPathDefault: ${config.cdn.domain}/WX/repository/tkp-agent-web/column/healthQuestionnaire/healthQuestionnaireItem.png
    #限制上传的单个文件的大小为10M[10485760]、20M[20971520]、50M[52428800]
    maxSize: 52428800
  learnWeb:
    host: http://wxyl.pension.taikang.com/tkp-learn-web
  job:
    taskTimeInterval: 60000