#01_server配置
server:
  port: 8887
  servlet: 
    context-path: /tkp-learn-web
      
#02_spring配置
spring:
  datasource:
    url: jdbc:mysql://10.153.57.107:3306/tkp-repository?characterEncoding=utf8&useSSL=false
    username: tkprepository
    password: "/tkprepository2018"
    dbcp2:
      initialSize: 2
      maxTotal: 5
      maxIdle: 5
      minIdle: 2
      maxWaitMillis: 1800
      test-while-idle: true
      # Oracle请使用select 1 from dual
      validation-query: select 'x'

#03_logger配置
logging:
  level:
    root: WARN
    "com.tkp": DEBUG
  pattern:
      console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n"
      file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n" 

#04_feign配置
feign:
  okhttp:
    enabled: true 
    
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#06_local project config配置
config:
  jwt:
    #单位：秒
    expiration: 1800
    secret: 25f029d402c20563bcfaf9fc34613ee6104646490d907a43ab49aea674510dc23a9ac47cd018db81a868894a42d564283756acbb78a8fa0ffe0d7f6d9951c693
    issuer: tkp-learn-web
  cross:
    flag: true
  tkpes:
    host: http://10.130.208.31:8204/tkp-agent-web
  #盟主视频签名对接
  mengzhu:
    appId: 2020030719365559007
    secret: QErplqm4cirbmgsXBipAfsvPBkBcKfkyJHmRPxgssDsdyzOXCnFnNXE4phcX0WQT
    systemCode: tkp-repository
    businessCode: OTO5GCourses
  video:
    #已完成判断标准
    thresholdRate: 0.9
  column:
    shareUrl: http://bbc.taikang.com/tkp-repository/#/index/goVideo?redirectUrl=##BASE64[$(redirectUrl)]
#07task config 批处理任务时间配置
time:
  cron:
    # 每日20点执行1次
    topListDetailToDay: 0 0 20 1/1 * ? *
MengZhu:
  appId: 2019091814213467319
  secret: RMyGZPSnCBQziQYsZK1aHGnuYzGbWRe9XX3TaBJdT1G9Ha30rfntEeFGpv7w0iI1
