#01_server配置
server:
  port: 8288
  servlet:
    context-path: /tkp-learn-archive-task
      
#02_spring配置
spring:
  datasource:
    url: jdbc:mysql://10.130.105.129:3306/tkp_repository?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: tkprepository
    password: "TKP#repository@2020"
    dbcp2:
      initialSize: 4
      maxTotal: 10
      maxIdle: 8
      minIdle: 4
      maxWaitMillis: 1000
      test-while-idle: true
      # Oracle请使用select 1 from dual
      validation-query: select 'x'

#03_logger配置
logging:
  level:
    root: WARN
    "com.tkp": ERROR
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n"

#04_feign配置
feign:
  okhttp:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

## 批处理配置
task:
  topListTask:
    ## 所有批处理的偏移量单位条
    deviationValue: 500
    handleDayTask:
      ## 启动后的第一个5分时开始执行，之后每5分钟执行一次
      cron: "0 0/5 * * * ?"
      initialDelay: 60000
      fixedRate: 60000
    handleTopListTask:
      cron: "0 0/10 * * * ?"
      initialDelay: 120000
      fixedRate: 3600000



