#01_server配置
server:
  port: 8291
  servlet:
    context-path: /tkp-learn-admin
      
#02_spring配置
spring:
  datasource:
    url: jdbc:mysql://10.153.57.107:3306/tkp-repository?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: tkprepository
    password: "/tkprepository2018"
    dbcp2:
      initialSize: 2
      maxTotal: 5
      maxIdle: 5
      minIdle: 2
      maxWaitMillis: 1800
      test-while-idle: true
      # Oracle请使用select 1 from dual
      validation-query: select 'x'

#03_logger配置
logging:
  level:
    root: INFO
    "com.tkp.learn.admin": DEBUG
  pattern:
      console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n"
      file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %level %logger{50} - %msg%n" 

#04_feign配置
feign:
  okhttp:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

#06_local project config配置
config:
  jwt:
    #单位：秒
    expiration: 36000
    secret: mod0w2ae5320563bcfaf9fc34613ee610464649w83hd4ea674510dc23a9acklhawe9hf9on39hfsasr123d995as0i83
    issuer: tkp-learn-admin
  cross:
    flag: false
  #泰运营端接口
  tkop:
    secretCode: dGtwX2xlYXJuX2FkbWluOjdmNTNkMWQ3NmE0NDQ5ZTQ4MzE0MTRkOGIwZWM0NmMw
    ssoUser: http://10.130.226.35:8301


